<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BEM FK Helvetia</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            color: #333;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #4CAF50;
            color: white;
            padding: 10px 0;
            text-align: center;
        }
        nav {
            text-align: center;
            padding: 15px;
        }
        nav a {
            margin: 0 10px;
            text-decoration: none;
            color: #333;
            font-weight: bold;
        }
        section {
            padding: 20px;
            text-align: center;
        }
        footer {
            background-color: #4CAF50;
            color: white;
            text-align: center;
            padding: 10px 0;
            position: fixed;
            width: 100%;
            bottom: 0;
        }
    </style>
</head>
<body>

<header>
    <h1>Selamat Datang di BEM FK Helvetia</h1>
</header>

<nav>
    <a href="#profil">Profil</a>
    <a href="#kegiatan">Kegiatan</a>
    <a href="#kontak">Kontak</a>
</nav>

<section id="profil">
    <h2>Profil BEM FK Helvetia</h2>
    <p>Badan Eksekutif Mahasiswa Fakultas Kedokteran Helvetia berkomitmen untuk memajukan mahasiswa melalui berbagai kegiatan, seminar, dan proyek sosial.</p>
</section>

<section id="kegiatan">
    <h2>Kegiatan Kami</h2>
    <p>Kami menyelenggarakan berbagai kegiatan seperti bakti sosial, seminar kesehatan, dan pengabdian masyarakat.</p>
</section>

<section id="kontak">
    <h2>Kontak Kami</h2>
    <p>Email: bemfk@helvetia.ac.id | Telp: 021-12345678</p>
</section>

<footer>
    <p>&copy; 2024 BEM FK Helvetia</p>
</footer>

</body>
</html>
